INSERT INTO games (name, description, image, genre, price) VALUES
('God of War', 'Acompanhando Kratos e seu filho Atreus em uma jornada cheia de ação, mitologia e emoção.', 'https://upload.wikimedia.org/wikipedia/pt/8/82/God_of_War_2018_capa.png', 'Ação', 249.9),
('The Witcher 3: Wild Hunt', 'Aventuras de Geralt de Rivia enquanto ele busca por sua filha adotiva em um mundo vasto e perigoso.', 'https://upload.wikimedia.org/wikipedia/pt/0/06/TW3_Wild_Hunt.png', 'RPG', 149.9),
('Minecraft', 'Construção e exploração em um mundo de blocos, com foco em sobrevivência e criatividade.', 'https://www.adrenaline.com.br/wp-content/uploads/2023/06/minecraft-capa.jpg', 'Simulação', 99.9),
('FIFA 23', 'Jogo de futebol com modos de jogo realistas, como FIFA Ultimate Team e Carreira.', 'https://cdn.jornaldaparaiba.com.br/wp-content/uploads/2022/07/FIFA-23.jpg?xid=702307', 'Esportes', 299.9),
('Among Us', 'Jogo de dedução social onde os jogadores devem descobrir quem é o impostor.', 'https://sm.ign.com/ign_br/cover/a/among-us/among-us_8kks.jpg', 'Festa', 29.9),
('Call of Duty: Modern Warfare II', 'Shooter de ação intensa, com foco em missões militares e combate online.', 'https://image.api.playstation.com/vulcan/ap/rnd/202306/2400/ac505d57a46e24dd96712263d89a150cb443af288c025ff2.jpg', 'Atirador', 199.9),
('Fortnite', 'Batalha real onde você constrói, luta e sobrevive até ser o último em pé.', 'https://s2-ge.glbimg.com/rTBwLqhxwmu0z4EiDYtbfislArI=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_bc8228b6673f488aa253bbcb03c80ec5/internal_photos/bs/2020/C/4/WC166yT0uMa85VkUrLTQ/15br-social-lineup-social-1920x1080-685054651.jpg', 'Atirador', 0.0),
('Resident Evil Village', 'Horror psicológico e ação em uma vila cheia de criaturas assustadoras e mistérios.', 'https://squared-potato.pt/wp-content/uploads/2021/01/Resident-Evil-Village-Capa.jpg', 'Terror', 179.9),
('Street Fighter V', 'Luta de rua com diversos personagens e estilos de combate únicos.', 'https://cdn.awsli.com.br/2500x2500/1041/1041512/produto/143491546/street-fighter-v---pc-c-digo-digital-hu2gpsqdts.jpg', 'Luta', 149.9),
('Gran Turismo 7', 'Simulador de corrida com gráficos realistas e uma vasta seleção de carros.', 'https://meups.com.br/wp-content/uploads/2022/03/Gran-Turismo-7-analise-vale-a-pena.jpg', 'Corrida', 249.9),
('Final Fantasy VII Remake', 'Remake do clássico RPG, com gráficos atualizados e combate em tempo real.', 'https://projetoitaca.com.br/wp-content/uploads/2022/09/finalfantasyviiremake11.jpeg', 'RPG', 199.9),
('Forza Horizon 5', 'Jogo de corrida de mundo aberto com gráficos impressionantes e uma grande variedade de carros.', 'https://store-images.s-microsoft.com/image/apps.33953.13806078025361171.9723cf5e-1e29-4d9d-ad0a-cc37a95bb75d.afabb748-2c30-4a7e-8072-2809a222192d?q=90&w=480&h=270', 'Corrida', 59.9),
('Apex Legends', 'Battle royale com equipes de heróis, cada um com habilidades únicas.', 'https://sm.ign.com/t/ign_br/screenshot/default/apex-legends-lendas_6emk.1200.jpg', 'Atirador', 0.0),
('Minecraft Dungeons', 'Jogo de ação e RPG ambientado no universo de Minecraft, com foco em masmorras.', 'https://assets1.ignimgs.com/2020/06/18/minecraft-dungeons-1280-1592460208159.jpg', 'RPG', 99.9),
('Overwatch 2', 'Jogo de tiro em equipe com heróis, cada um com habilidades únicas e trabalho em equipe essencial.', 'https://blz-contentstack-images.akamaized.net/v3/assets/bltf408a0557f4e4998/blte7acaf850e5d532d/67576d548c2c1d7026faad29/OW2_2024_S14-Launch-BNET_SHOP-browsingcard_1920x1080.png', 'Atirador', 179.9),
('Red Dead Redemption 1', 'Aventura no Velho Oeste, com um vasto mundo aberto e uma história épica.', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Red_Dead_Redemption.jpg/220px-Red_Dead_Redemption.jpg', 'Aventura', 249.9),
('Rocket League', 'Futebol com carros, onde você dirige veículos em arenas e tenta marcar gols.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJANR1OZtB3WTef1I80MZGu8t93BEfj5BfXg&s', 'Esportes', 99.9),
('The Elder Scrolls V: Skyrim', 'RPG de mundo aberto, onde você explora um vasto reino e luta contra dragões.', 'https://image.api.playstation.com/vulcan/ap/rnd/202009/2820/h12URI7MdswtFPFHpkppNh2z.png', 'RPG', 129.9),
('Assassin''s Creed Valhalla', 'Aventura e ação com vikings, onde você explora terras antigas e participa de batalhas épicas.', 'https://dicaspc.com.br/wp-content/uploads/2021/12/37b8cbaf-b0f9-4089-b264-bfeb857af868.jpg', 'Aventura', 199.9),
('Dark Souls III', 'RPG de ação desafiador com combates intensos e uma narrativa sombria.', 'https://assets.nuuvem.com/image/upload/v1/products/5703b88ed27734565a000045/sharing_images/khotnvdk8lir2sjxmfst.jpg', 'RPG', 149.9),
('Cyberpunk 2077', 'RPG de mundo aberto em um futuro distópico.', 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRWH8K2baa5QsbGLwLgdOBoCgAH8G-tts6ljcfY3mdpYjy4QjtJxuaAPeTM3asitg9ti_Mf', 'RPG', 199.9),
('The Legend of Zelda: Breath of the Wild', 'Aventura épica em um mundo aberto.', 'https://upload.wikimedia.org/wikipedia/pt/thumb/0/0f/Legend_of_Zelda_Breath_of_the_Wild_capa.png/270px-Legend_of_Zelda_Breath_of_the_Wild_capa.png', 'Aventura', 299.9),
('Super Mario Odyssey', 'Aventura de plataforma com Mario.', 'https://www.metacritic.com/a/img/catalog/provider/6/12/6-1-624965-52.jpg', 'Plataforma', 249.9),
('Horizon Zero Dawn', 'Ação em um mundo pós-apocalíptico.', 'https://m.media-amazon.com/images/M/MV5BNGY2NjUzOTItMjkzNS00NzNiLWIwY2MtMzQ3MDIwY2RlNjdjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg', 'Ação', 199.9),
('Animal Crossing: New Horizons', 'Simulação de vida em uma ilha paradisíaca.', 'https://upload.wikimedia.org/wikipedia/id/thumb/1/1f/Animal_Crossing_New_Horizons.jpg/220px-Animal_Crossing_New_Horizons.jpg', 'Simulação', 249.9),
('Doom Eternal', 'FPS intenso com demônios e ação frenética.', 'https://store-images.s-microsoft.com/image/apps.19006.14633846388270955.34167af5-fabe-4bb4-87d1-87f313b6f79c.04c39d71-02b4-4f11-8a36-90dcb5326abe?h=862&format=jpg', 'Atirador', 179.9),
('Stardew Valley', 'Simulação de fazenda e vida rural.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkeLlFQDTHsYjSHtbBsInAYl2aIF54Qz_8zQ&s', 'Simulação', 59.9),
('The Last of Us Part II', 'Ação e sobrevivência em um mundo pós-apocalíptico.', 'https://upload.wikimedia.org/wikipedia/pt/9/96/The_Last_of_Us_2_capa.png', 'Ação', 199.9),
('Hades', 'Roguelike de ação com mitologia grega.', 'https://upload.wikimedia.org/wikipedia/pt/8/80/Hades_capa.jpg', 'Roguelike', 99.9),
('Among Trees', 'Exploração e sobrevivência em uma floresta.', 'https://assets-prd.ignimgs.com/2022/08/17/amongtrees-1660695102598.jpg', 'Sobrevivência', 49.9),
('Celeste', 'Plataforma desafiador com uma história emocionante.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Celeste_box_art_full.png/800px-Celeste_box_art_full.png', 'Plataforma', 69.9),
('Dead Cells', 'Roguelike de ação com combate rápido.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRitF38kKfmZ9SbVYiPT6KYHWMuEQLHIa78AA&s', 'Roguelike', 79.9),
('Cuphead', 'Plataforma com estilo visual único e desafios difíceis.', 'https://upload.wikimedia.org/wikipedia/pt/c/c1/Cuphead_capa.png', 'Plataforma', 89.9),
('Ori and the Blind Forest', 'Aventura emocionante em um mundo mágico.','https://lastfm.freetls.fastly.net/i/u/ar0/d4cd73f0adeac87a8951ff3ade82f300.jpg','Metroidvania',99.9),
('Hollow Knight', 'Metroidvania com exploração e combate desafiador.', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Hollow_Knight_first_cover_art.webp/274px-Hollow_Knight_first_cover_art.webp.png', 'Metroidvania', 59.9),
('Portal 2', 'Quebra-cabeças com portais e física única.', 'https://upload.wikimedia.org/wikipedia/pt/f/f9/Portal2cover.jpg', 'Quebra-cabeça', 49.9),
('Bloodborne', 'RPG de ação desafiador com combates intensos.', 'https://assets-prd.ignimgs.com/2024/11/24/bloodborneconcord2-1732446312120.jpg', 'RPG', 149.9),
('Outlast 2', 'Sobreviva a horrores em um ambiente assustador.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkIu8SKmaiAF-PKEqR3pFnf18X_8t0y87NBA&s', 'Terror', 129.9),
('Sekiro: Shadows Die Twice', 'Ação e aventura com combate preciso.', 'https://upload.wikimedia.org/wikipedia/pt/7/7b/Sekiro_Shadows_Die_Twice_capa.png', 'Ação', 199.9),
('Monster Hunter: World', 'Caça a monstros em um mundo vasto.', 'https://upload.wikimedia.org/wikipedia/pt/3/34/Monster_Hunter_World_capa.jpg', 'Ação', 149.9),
('Ghost of Tsushima', 'Ação e aventura em um mundo samurai.', 'https://upload.wikimedia.org/wikipedia/pt/d/dc/Ghost_of_Tsushima_capa.png', 'Ação', 199.9),
('Spider-Man: Miles Morales', 'Ação e aventura com o Homem-Aranha.', 'https://upload.wikimedia.org/wikipedia/pt/7/74/Spider-Man_Miles_Morales_capa.png', 'Ação', 249.9),
('Assassin''s Creed Odyssey', 'RPG de mundo aberto na Grécia Antiga.', 'https://upload.wikimedia.org/wikipedia/en/9/99/ACOdysseyCoverArt.png', 'RPG', 149.9),
('Red Dead Redemption 2', 'Mundo aberto de faroeste e aventura.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6Zw3ba8igTlqTD-rCWWQgpjA1dFwTv0DV3w&s', 'Aventura', 199.9),
('Death Stranding', 'Ação e exploração em um mundo pós-apocalíptico.', 'https://upload.wikimedia.org/wikipedia/pt/e/eb/Death-Stranding-poster.jpg', 'Ação', 179.9),
('Control', 'Ação e tiro em um ambiente surreal.', 'https://upload.wikimedia.org/wikipedia/pt/7/73/Control_capa.png', 'Ação', 129.9),
('The Outer Worlds', 'RPG de ficção científica com escolhas impactantes.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7ku4d9PtByjdTGqU3KOeRyOa7tFsaxAah4Q&s', 'RPG', 149.9),
('Disco Elysium', 'RPG investigativo com foco em diálogos.', 'https://www.adrenaline.com.br/wp-content/uploads/2023/08/disco-elysium-the-final-cut-capa.jpg', 'RPG', 99.9),
('Fire Emblem: Three Houses', 'RPG tático com estratégia e personagens cativantes.', 'https://upload.wikimedia.org/wikipedia/pt/c/c8/Fire_Emblem_Three_Houses_capa.png', 'RPG', 199.9),
('Persona 5 Royal', 'RPG com uma história envolvente e estilo único.', 'https://preview.redd.it/whats-the-best-and-worst-confidant-in-persona-5-royal-story-v0-tz283zn1tszb1.jpg?width=1080&crop=smart&auto=webp&s=d663f557c689506bd06aea2c59e5c10303695b36', 'RPG', 249.9),
('Final Fantasy VII Remake', 'Remake do clássico RPG com gráficos modernos.', 'https://upload.wikimedia.org/wikipedia/en/c/ce/FFVIIRemake.png', 'RPG', 199.9),
('Nier: Automata', 'Ação e RPG em um mundo pós-apocalíptico.', 'https://upload.wikimedia.org/wikipedia/pt/1/15/Nier_Automata_capa.png', 'RPG', 149.9),
('Divinity: Original Sin 2', 'RPG tático com liberdade de escolha.', 'https://upload.wikimedia.org/wikipedia/pt/4/4a/Divinity_Original_Sin_II_Larian_Studios_key_art.png', 'RPG', 129.9),
('Xenoblade Chronicles 2', 'RPG de mundo aberto com uma história épica.', 'https://upload.wikimedia.org/wikipedia/en/4/4a/Xenoblade_Chronicles_2.jpg', 'RPG', 199.9),
('Octopath Traveler', 'RPG com estilo visual único e histórias interligadas.', 'https://m.media-amazon.com/images/I/91MPynJRxgL._AC_UF1000,1000_QL80_.jpg', 'RPG', 149.9),
('Dragon Quest XI', 'RPG clássico com uma jornada épica.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTucX51ce_6u19xiJMTdoHl5a-WpW7KG32zUQ&s', 'RPG', 179.9),
('The Legend of Heroes: Trails of Cold Steel', 'RPG com foco em história e personagens.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpgoT-dmYVSbAZeZwP57T-3Ih5JHPxd3VDFg&s', 'RPG', 129.9),
('Ys IX: Monstrum Nox', 'RPG de ação com exploração e combate rápido.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqJGH0IWUngB5bEEvIszxQKeBEubdyjRD2lA&s', 'RPG', 149.9),
('Tales of Arise', 'RPG de ação com gráficos impressionantes.', 'https://store-images.s-microsoft.com/image/apps.53840.14220579343208919.30d737b4-d1cd-4f53-ae6f-df6cc7a21450.5106ecb4-abee-48bd-9f3b-0600583211da?q=90&w=480&h=270', 'RPG', 199.9),
('Genshin Impact', 'RPG de mundo aberto com elementos de ação.', 'https://img.odcdn.com.br/wp-content/uploads/2021/03/Genshin-Impact-capa.jpg', 'RPG', 0.0),
('League of Legends', 'Jogo de estratégia e batalha online.', 'https://s2-ge.glbimg.com/fxI0yK-cdnMNI2FrieyuHcdCtkE=/0x0:984x554/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_bc8228b6673f488aa253bbcb03c80ec5/internal_photos/bs/2021/6/Q/Fq6AMUTJKxZA7SVgIJBA/league-of-legends.jpg', 'MOBA', 0.0),
('Dota 2', 'Jogo de estratégia e batalha online.', 'https://upload.wikimedia.org/wikipedia/en/3/31/Dota_2_Steam_artwork.jpg', 'MOBA', 0.0),
('Grand Theft Auto V', 'Mundo aberto com ação e missões variadas.', 'https://upload.wikimedia.org/wikipedia/pt/8/80/Grand_Theft_Auto_V_capa.png', 'Ação', 50.0),
('Planet Zoo', 'Construa e gerencie seu próprio zoológico.', 'https://upload.wikimedia.org/wikipedia/pt/a/aa/Planet_Zoo_capa_digital.jpg', 'Simulação', 30.0),
('Cities: Skylines', 'Construa e gerencie sua própria cidade.', 'https://upload.wikimedia.org/wikipedia/pt/5/58/Cities_Skylines_cover_art.jpg', 'Simulação', 30.0),
('Euro Truck Simulator 2', 'Simulador de caminhões com viagens pela Europa.', 'https://upload.wikimedia.org/wikipedia/en/0/0e/Euro_Truck_Simulator_2_cover.jpg', 'Simulação', 15.0),
('Skate 3', 'Jogo de skate com desafios e competições.', 'https://upload.wikimedia.org/wikipedia/pt/8/84/Skate-3-Boxart.jpg', 'Esportes', 60.0),
('Tony Hawk''s Pro Skater 1 + 2', 'Remake dos clássicos jogos de skate.', 'https://d.newsweek.com/en/full/1589297/tony-hawks-pro-skater-1-2-remaster.jpg?w=1200&f=76344179471c9980457e97bf7b9298b6', 'Esportes', 60.0),
('F1 2024', 'Corrida de Fórmula 1 com gráficos realistas.', 'https://uploads.folhavitoria.com.br/2024/11/WFmkWIkK-a3a83a80-fe64-11ee-b496-839201a2b71e-png.webp', 'Esportes', 60.0),
('Lethal Company', 'Sobreviver e explorar em planetas de forma COOP', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIjZ8Y7AA2x3vnyeAdzeiz8r2CUBlG-lvKbw&s', 'Festa', 60.0),
('BATTELFIELD 1', 'Jogo de guerra com gráficos realistas.', 'https://upload.wikimedia.org/wikipedia/pt/7/75/Battlefield_1_capa.png', 'Atirador', 60.0),
('Need For Speed', 'Corrida de carros com muita velocidade.', 'https://img.redbull.com/images/c_crop,x_210,y_0,h_800,w_640/c_fill,w_450,h_600/q_auto:low,f_auto/redbullcom/2015/08/11/1331740714779_2/need-for-speed', 'Corrida', 60.0),
('Phasmophobia', 'Jogo de terror com caça a fantasmas.', 'https://i.scdn.co/image/ab67616d00001e0268d6c84d05d26849d7d3ddf9', 'Terror', 60.0),
('Silent Hill 2 Remake', 'Remake do clássico jogo de terror.', 'https://i0.wp.com/ovicio.com.br/wp-content/uploads/2023/01/20230105-ovicio-silent-hill-remake-6.jpg?resize=555%2C555&ssl=1', 'Terror', 60.0),
('Mortal Kombat 11', 'Jogo de luta com personagens icônicos.', 'https://upload.wikimedia.org/wikipedia/pt/2/21/Mortal_Kombat_11_capa.jpg', 'Luta', 60.0),
('Injustice 2', 'Jogo de luta com personagens da DC Comics.', 'https://store-images.s-microsoft.com/image/apps.51626.13806078025361171.73ef9826-822a-4a0b-ab4a-4fe8fd87fc3b.714f1b5c-6793-443d-a291-74b81479dc92', 'Luta', 60.0),
('Tekken 7', 'Jogo de luta com personagens icônicos.', 'https://upload.wikimedia.org/wikipedia/pt/thumb/1/11/Tekken_7_capa.png/270px-Tekken_7_capa.png', 'Luta', 60.0),
('SAMURAI SHODOWN NEOGEO COLLECTION', 'Jogo de luta com personagens icônicos.', 'https://store-images.s-microsoft.com/image/apps.58186.13674646977960925.9db53c0b-a3b6-490f-938f-013f9c73f901.036ebeb9-1979-4b4d-b37c-d0acc8e87fb7', 'Luta', 60.0),
('Metroid Dread', 'Ação e aventura com a caçadora de recompensas Samus Aran.', 'https://upload.wikimedia.org/wikipedia/pt/thumb/5/50/Metroid-Dread-capa.jpeg/270px-Metroid-Dread-capa.jpeg', 'Metroidvania', 400.0),
('Blasphemous', 'Metroidvania com combate desafiador e visual único.', 'https://www.adrenaline.com.br/wp-content/uploads/2023/04/blasphemous-capa.jpg', 'Metroidvania', 20.0),
('Castlevania: Symphony of the Night', 'Clássico jogo de ação e exploração.', 'https://i.scdn.co/image/ab67616d0000b273aafa93f5ac3b3b9a22727862', 'Metroidvania', 20.0),
('There is No Game: Wrong Dimension', 'Jogo de aventura e quebra-cabeça com uma narrativa única.', 'https://assets-prd.ignimgs.com/2021/04/26/there-is-no-game-button-01-1619472403964.jpg', 'Quebra-cabeça', 20.0),
('Final Fantasy XIV Online', 'MMORPG com uma história épica e muitas classes.', 'https://www.adrenaline.com.br/wp-content/uploads/2023/07/final-fantasy-xiv-capa.jpg', 'MMORPG', 20.0),
('World of Warcraft', 'MMORPG onde você cria um personagem e explora um mundo vasto e dinâmico.', 'https://sm.ign.com/ign_br/news/w/world-of-w/world-of-warcraft-subscriber-numbers-fall-to-55-mi_z5wg.jpg', 'MMORPG', 29.99),
('DIABLO III', 'RPG de ação com muitos inimigos e loot.', 'https://upload.wikimedia.org/wikipedia/pt/1/12/DiabloIIIcover.jpg', 'MMORPG', 20.0),
('Don''t Starve', 'Jogo de sobrevivência com elementos de crafting e exploração.', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgOWpLTWiMYp1vkeGpyYB337aWUgYT-8kfHJ4zx4_1Quz6UH9JNejPYHN_X6AxZMRRMWBSrmktGpRZJv9hJZAtzhyphenhyphen6XziztRkaPLkh6yGoJjZXTnzSZtBZBSfhLKPdpX6hsH1tVq4cygg/s1600/dont+starve.jpg', 'Sobrevivência', 20.0),
('The Forest', 'Jogo de sobrevivência com elementos de terror.', 'https://cdn-offer-photos.zeusx.com/4e5b7d20-6a9d-40c2-b14c-16d5d93bf0d4.jpg', 'Sobrevivência', 20.0),
('Ark Survival Evolved', 'Jogo de sobrevivência e crafting com Dinossauros.', 'https://upload.wikimedia.org/wikipedia/pt/d/d0/Ark_Survival_Evolved_%C3%ADcone_digital_Nintendo_Switch_Studio_Wildcard.png', 'Sobrevivência', 20.0),
('Sid Meier''s Civilization VI', 'Jogo de Estratégia com civilizações Históricas.', 'https://www.adrenaline.com.br/wp-content/uploads/2023/07/sid-meiers-civilization-vi-capa.jpg', 'Estratégia', 20.0),
('Hearts of Iron IV', 'Jogo de Estratégia para você comandar qualquer nação na segunda guerra mundial.', 'https://upload.wikimedia.org/wikipedia/pt/1/11/Hearts_of_Iron_IV.jpg', 'Estratégia', 20.0),
('Astro Bot', 'Jogo de Plataforma', 'https://upload.wikimedia.org/wikipedia/pt/thumb/5/5c/Astro_Bot.webp/640px-Astro_Bot.webp.png', 'Plataforma', 20.0),
('Star Wars Jedi Fallen Order', 'Jogo de Aventura que você controla Cal Kestis um Padawan que virou Fugitivo', 'https://upload.wikimedia.org/wikipedia/pt/thumb/9/96/Star_Wars_Jedi_Fallen_Order_capa.png/270px-Star_Wars_Jedi_Fallen_Order_capa.png', 'Aventura', 20.0);