INSERT INTO games (name, description, image, genre, price) VALUES
('The Legend of Zelda: Breath of the Wild', 'Aventura épica em um mundo aberto, onde você explora, luta e resolve quebra-cabeças.', 'zelda_breath_of_the_wild.jpg', 'ADVENTURE', 199.99),
('God of War', 'Acompanhando Kratos e seu filho Atreus em uma jornada cheia de ação, mitologia e emoção.', 'god_of_war.jpg', 'ACTION', 249.90),
('The Witcher 3: Wild Hunt', 'Aventuras de Geralt de Rivia enquanto ele busca por sua filha adotiva em um mundo vasto e perigoso.', 'witcher_3.jpg', 'RPG', 149.90),
('Minecraft', 'Construção e exploração em um mundo de blocos, com foco em sobrevivência e criatividade.', 'minecraft.jpg', 'SIMULATION', 99.90),
('FIFA 23', 'Jogo de futebol com modos de jogo realistas, como FIFA Ultimate Team e Carreira.', 'fifa_23.jpg', 'SPORTS', 299.90),
('Among Us', 'Jogo de dedução social onde os jogadores devem descobrir quem é o impostor.', 'among_us.jpg', 'PARTY', 29.90),
('Call of Duty: Modern Warfare II', 'Shooter de ação intensa, com foco em missões militares e combate online.', 'cod_modern_warfare_2.jpg', 'SHOOTER', 199.90),
('Fortnite', 'Batalha real onde você constrói, luta e sobrevive até ser o último em pé.', 'fortnite.jpg', 'RACING', 0.00),
('Resident Evil Village', 'Horror psicológico e ação em uma vila cheia de criaturas assustadoras e mistérios.', 'resident_evil_village.jpg', 'HORROR', 179.90),
('Street Fighter V', 'Luta de rua com diversos personagens e estilos de combate únicos.', 'street_fighter_v.jpg', 'FIGHTING', 149.90),
('Gran Turismo 7', 'Simulador de corrida com gráficos realistas e uma vasta seleção de carros.', 'gran_turismo_7.jpg', 'RACING', 249.90),
('Final Fantasy VII Remake', 'Remake do clássico RPG, com gráficos atualizados e combate em tempo real.', 'final_fantasy_vii_remake.jpg', 'RPG', 199.90),
('Hollow Knight', 'Jogo de plataforma metroidvania com exploração e combate desafiador.', 'hollow_knight.jpg', 'METROIDVANIA', 59.90),
('Apex Legends', 'Battle royale com equipes de heróis, cada um com habilidades únicas.', 'apex_legends.jpg', 'SHOOTER', 0.00),
('Minecraft Dungeons', 'Jogo de ação e RPG ambientado no universo de Minecraft, com foco em masmorras.', 'minecraft_dungeons.jpg', 'RPG', 99.90),
('Overwatch 2', 'Jogo de tiro em equipe com heróis, cada um com habilidades únicas e trabalho em equipe essencial.', 'overwatch_2.jpg', 'SHOOTER', 179.90),
('Red Dead Redemption 2', 'Mundo aberto de faroeste, onde você segue a história de Arthur Morgan e sua gangue.', 'red_dead_redemption_2.jpg', 'ADVENTURE', 249.90),
('Rocket League', 'Futebol com carros, onde você dirige veículos em arenas e tenta marcar gols.', 'rocket_league.jpg', 'SPORTS', 99.90),
('The Elder Scrolls V: Skyrim', 'RPG de mundo aberto, onde você explora um vasto reino e luta contra dragões.', 'skyrim.jpg', 'RPG', 129.90),
('Assassin''s Creed Valhalla', 'Aventura e ação com vikings, onde você explora terras antigas e participa de batalhas épicas.', 'assassins_creed_valhalla.jpg', 'ADVENTURE', 199.90),
('Dark Souls III', 'RPG de ação desafiador com combates intensos e uma narrativa sombria.', 'dark_souls_3.jpg', 'RPG', 149.90),
('Tetris', 'Clássico jogo de quebra-cabeças onde você deve encaixar blocos para eliminar linhas.', 'tetris.jpg', 'PUZZLE', 19.90),
('The Sims 4', 'Simulação de vida onde você controla personagens em sua rotina diária, criando suas próprias histórias.', 'the_sims_4.jpg', 'SIMULATION', 129.90),
('Uncharted 4: A Thief''s End', 'Aventura cheia de ação, onde Nathan Drake busca tesouros escondidos em diferentes locais ao redor do mundo.', 'uncharted_4.jpg', 'ADVENTURE', 199.90),
('Monster Hunter: World', 'Caça monstros gigantes em um mundo vasto, com batalhas e itens para melhorar seu personagem.', 'monster_hunter_world.jpg', 'ACTION', 249.90),
('League of Legends', 'MOBA competitivo onde equipes batalham para destruir a base inimiga.', 'league_of_legends.jpg', 'MOBA', 0.00),
('League of Legends Wild Rift', 'Versão móvel e simplificada de League of Legends, com batalhas rápidas e ação intensa.', 'wild_rift.jpg', 'MOBA', 0.00),
('Cyberpunk 2077', 'RPG futurista ambientado em Night City, com narrativa envolvente e ação intensa.', 'cyberpunk_2077.jpg', 'RPG', 199.90),
('Doom Eternal', 'Shooter em primeira pessoa com ação frenética e combate contra demônios.', 'doom_eternal.jpg', 'SHOOTER', 149.90),
('Star Wars Jedi: Fallen Order', 'Jogo de ação e aventura em Star Wars, onde você assume o papel de um Jedi em treinamento.', 'fallen_order.jpg', 'ACTION', 199.90),
('Super Mario Odyssey', 'Aventura de plataforma onde Mario viaja por diferentes mundos para resgatar a Princesa Peach.', 'super_mario_odyssey.jpg', 'PLATFORMER', 249.90),
('Pokémon Sword and Shield', 'Jogo de RPG onde você captura e treina Pokémon para se tornar o campeão.', 'pokemon_sword_shield.jpg', 'RPG', 249.90),
('Bloodborne', 'RPG de ação com temática gótica, onde você enfrenta criaturas horríveis em uma cidade sombria.', 'bloodborne.jpg', 'HORROR', 179.90),
('Metroid Dread', 'Jogo de plataforma e exploração com a famosa caçadora de recompensas, Samus Aran.', 'metroid_dread.jpg', 'METROIDVANIA', 179.90),
('Fable III', 'RPG com escolhas morais e um mundo aberto, onde suas decisões afetam o futuro do reino.', 'fable_iii.jpg', 'RPG', 149.90),
('Minecraft: Story Mode', 'Jogo de aventura baseado no universo de Minecraft, com uma história interativa e escolhas.', 'minecraft_story_mode.jpg', 'ADVENTURE', 79.90),
('World of Warcraft', 'MMORPG onde você cria um personagem e explora um mundo vasto e dinâmico.', 'world_of_warcraft.jpg', 'MMORPG', 29.99),
('Spelunky 2', 'Plataforma roguelike onde você explora cavernas em busca de riquezas e enfrenta desafios aleatórios.', 'spelunky_2.jpg', 'PLATFORMER', 49.90),
('Fall Guys', 'Battle royale com mini-jogos e competição em equipe, em um mundo colorido e divertido.', 'fall_guys.jpg', 'PARTY', 59.90),
('Cuphead', 'Jogo de plataforma e ação com gráficos inspirados nos desenhos animados dos anos 1930 e uma jogabilidade difícil.', 'cuphead.jpg', 'PLATFORMER', 79.90),
('Sekiro: Shadows Die Twice', 'Ação e aventura com samurais, onde você luta contra inimigos e aprende novas habilidades.', 'sekiro.jpg', 'ACTION', 249.90),
('The Last of Us Part II', 'Jogo de ação e aventura, com uma história emocionalmente impactante e uma jornada de vingança e redenção.', 'last_of_us_2.jpg', 'ADVENTURE', 229.90),
('The Forest', 'Jogo de sobrevivência onde você deve lutar contra criaturas e construir abrigos em uma ilha misteriosa.', 'the_forest.jpg', 'SURVIVAL', 79.90),
('No Man''s Sky', 'Exploração espacial e sobrevivência em um universo gerado proceduralmente, onde você pode visitar planetas desconhecidos.', 'no_mans_sky.jpg', 'SIMULATION', 149.90),
('Tomb Raider', 'Aventura com Lara Croft em busca de artefatos históricos e desvendando mistérios antigos.', 'tomb_raider.jpg', 'ADVENTURE', 129.90),
('Far Cry 5', 'Jogo de tiro em primeira pessoa com um mundo aberto e uma história sobre sequestros e manipulação em uma seita.', 'far_cry_5.jpg', 'ACTION', 199.90),
('Hades', 'Roguelike com ação rápida e combate envolvente, onde você tenta escapar do submundo como o filho de Hades.', 'hades.jpg', 'ACTION', 89.90),
('Bioshock Infinite', 'Jogo de tiro e ação com uma história envolvente sobre realidade alternativa e política.', 'bioshock_infinite.jpg', 'ACTION', 129.90),
('Assassin''s Creed Odyssey', 'Aventura e ação na Grécia Antiga, onde você explora, luta e toma decisões que afetam a história.', 'assassins_creed_odyssey.jpg', 'ADVENTURE', 199.90),
('Lords Mobile', 'Estratégia em tempo real, onde você constrói seu império e luta contra inimigos.', 'lords_mobile.jpg', 'STRATEGY', 0.00),
('Sid Meier''s Civilization VI', 'Jogo de estratégia onde você constrói uma civilização e compete contra outras para dominar o mundo.', 'civilization_vi.jpg', 'STRATEGY', 119.90);