spring:
  application:
    name: backend
  datasource: 
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: admin
  flyway:
    enabled: true
    locations: classpath:db/migration